### ISSUE TITLE
Missing or incorrect 183A Phase III image.

### ISSUE THREAD

**Issue by fleeting** [WSP-Denver/CTRMA-Interactive-Map#6]
Hey @benrudolphWSP 

For 183A Phase III, the image referenced in the gallery is `./images/183A_III/11062018_183AP3_Open-House-Boards.png` (https://github.com/WSP-Denver/CTRMA-Interactive-Map/blob/master/include/183A_Phase_III.html#L50) but that image doesn't exist. There is a second image for 183A Phase III (https://github.com/WSP-Denver/CTRMA-Interactive-Map/tree/master/images/183A_III) so not sure if it just needs to be renamed or the code should be changed to match the new image.

**Comment by benrudolphWSP** [comment]
Fixed with commit [2c0cec571e](https://github.com/WSP-Denver/CTRMA-Interactive-Map/commit/2c0cec571e73da9f9975977e66e192a934f8a034)
